server:
  port: 8000

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/znyw?userUnicode=true&characterEncoding=utf8&userSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 19921209











